### ISSUE TITLE
Create peak detection for IR and Red buffer values

### ISSUE THREAD

**Issue by yukitfoo** [2468513H/VigiSense#27]
refer to library for inspiration. 

We want to input a buffer for IR and red, using one of the buffers, get the peak value and obtain the AC vale (distance between peak and trough). 

https://github.com/DKARDU/heartrateNbloodoxygen/blob/main/Pulse.cpp

**Comment by yukitfoo** [comment]
Do issue 28 first (DC value)

**Comment by YznH1** [comment]
Peak detection applied
