### ISSUE TITLE
Create calculation for SPO2 using formula of ACDC of IR and Red sensor

### ISSUE THREAD

**Issue by yukitfoo** [2468513H/VigiSense#30]
![image](https://github.com/2468513H/VigiSense/assets/77401199/ac6438d2-7c53-4617-a061-900e17e23af5)
github wiki:  /max3010x-ev-kits-recommended-configurations-and-operating-profiles.pdf

**Comment by YznH1** [comment]
Calculation done and implemented in MAX30102 sensor specific class
