### ISSUE TITLE
Sensor Library 

### ISSUE THREAD

**Issue by YznH1** [2468513H/VigiSense#4]
Find the appropriate sensor library.

**Comment by yukitfoo** [comment]
Found this [library ](https://github.com/DFRobot/DFRobot_MAX30102/blob/master/example/SPO2/SPO2.ino) not sure if its usable but seems good enough to at least give it a go.

**Comment by YznH1** [comment]
Two possible libraries: 

•	https://github.com/garrettluu/max30102-rpi
•	https://github.com/DKARDU/heartrateNbloodoxygen (Originally meant for Arduino)

**Comment by yukitfoo** [comment]
Able to detect sensor with [arduino library.](https://github.com/sparkfun/SparkFun_MAX3010x_Sensor_Library/tree/master) Showing sensor to be working. Arduino used only to test if sensor works. 
 [video](https://gla-my.sharepoint.com/:v:/g/personal/2441458f_student_gla_ac_uk/EWpc2u9EBxFFozTUy6_SW_EBY45ZS7tMYyBzWD2mOUnaUQ?e=tfngMN&nav=eyJwbGF5YmFja09wdGlvbnMiOnt9LCJyZWZlcnJhbEluZm8iOnsicmVmZXJyYWxBcHAiOiJUZWFtcyIsInJlZmVycmFsTW9kZSI6InZpZXciLCJyZWZlcnJhbFZpZXciOiJwb3N0cm9sbC1jb3B5bGluay0yIiwicmVmZXJyYWxQbGF5YmFja1Nlc3Npb25JZCI6ImIxMjE4NDY3LWM0ZTctNGM4MS1hMThiLTE3YTVlOWIzYTE2NiJ9fQ%3D%3D)
